config/routes.rb
Rails.application.routes.draw do

  resources :users

  root 'github#index'

  #login logout authentication logic
  match '/logout' => 'sessions#destroy', via: %i(get delete), as: :logout
  match '/login' => 'sessions#new', via: %i(get), as: :login
  match '/auth/:service/callback' => 'services#create', via: %i(get post)
  match '/auth/failure' => 'services#failure', via: %i(get post)
  resources :services, only: %i(index create destroy)



  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/service.rb
class Service < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :services
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_filter :current_user, :require_login

  helper_method :logged_in?
  helper_method :current_user
  helper_method :current_service

  protected
  def current_user
    @current_user ||= User.find(session[:user_id]) if session.has_key?(:user_id)
  rescue ActiveRecord::RecordNotFound
    session[:user_id] = nil
  end

  def current_service
    if session.has_key?(:service_id)
      @current_service ||= Service.where(user_id: session[:user_id], id: session[:service_id]).first
    end
  rescue ActiveRecord::RecordNotFound
    session[:service_id] = nil
  end

  def require_login
    unless current_user
      redirect_to login_path
    end
  end

  def current_user?
    !!current_user
  end

  def logged_in?
    current_user?
  end

  def authenticate_user!
    if session.has_key?(:user_id)
      current_user
    else
      redirect_to redirect_path
    end
  end

  def logout!
    @current_user = nil
    reset_session
  end

  def redirect_path
    :root
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  skip_before_filter :verify_authenticity_token, :require_login
  def index
    @providers     ||= omniauth_providers
    @user_services   = current_user.services
  end

  def create
    current_service = Service.where(provider: omnihash[:provider], uid: omnihash[:uid]).first

    if logged_in?
      if current_service
        flash[:notice] = I18n.t('notifications.provider_already_connected', provider: omnihash[:provider])
      else
        current_user.services.create!({
          provider: omnihash[:provider],
          uid: omnihash[:uid]
        })

        flash[:notice] = I18n.t('notifications.provider_added', provider: omnihash[:provider])
      end
    else
      if current_service
        session[:user_id]            = current_service.user.id
        session[:service_id]         = current_service.id
        session[:oauth_token]        = omnihash[:credentials][:token]
        session[:oauth_token_secret] = omnihash[:credentials][:secret]
      else
        user         = User.new
        user.name    = omnihash[:info][:name] #not sure if all users will have names associated with their accounts
        user.name    = omnihash[:info][:name] if omnihash[:provider].to_s == "developer"
        user.email   = omnihash[:info][:email]
        user_service = user.services.build({
          provider: omnihash[:provider],
          uid: omnihash[:uid]
        })

        if user.save!
          session[:user_id]            = user.id
          session[:service_id]         = user_service.id
          session[:oauth_token]        = omnihash[:credentials][:token]
          session[:oauth_token_secret] = omnihash[:credentials][:secret]

          flash[:notice] = I18n.t('notifications.account_created')
        end
      end
    end

    redirect_to root_url #services_path
  end

  def destroy
    service = current_user.services.find(params[:id])
    if service.respond_to?(:destroy) and service.destroy
      flash[:notice] = I18n.t('notifications.provider_unlinked', provider: service.provider)
      redirect_to redirect_path
    end
  end

  def failure
    flash[:error] = I18n.t('notifications.authentication_error')
    redirect_to root_url
  end

  private
  def omnihash
    request.env['omniauth.auth']
  end

  def omniauth_providers
    (OmniAuth::Strategies.local_constants.map(&:downcase) - %i(developer oauth oauth2)).map(&:to_s)
  end

  def redirect_path
    :services
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_filter :require_login
  def new; end

  def destroy
    logout!
    redirect_to root_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(page_title)
    content_for(:title) { page_title.to_s }
  end

  def yield_or_default(section, default = '')
    content_for?(section) ? content_for(section) : default
  end

  def active_nav(actionName)
    if params[:action] == actionName
      'active'
    end
  end
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/github/index.html.erb
<h1>We are in the github index view</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang='<%= I18n.locale.to_s %>'>
<head>
  <meta charset='utf-8'>
  <meta content='width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0' name='viewport'>
  <title>
    <%= yield_or_default :title, controller.action_name.titlecase %>
  </title>
  <%= csrf_meta_tags %>
  <%= yield :head %>


<!-- HTML5 shim, for IE6-8 support of HTML elements -->
<!--[if lt IE 9]>
<script src="https://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
<![endif]-->

<%= stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Ubuntu:400,500,700', 'application', media: 'all' %>

<!-- Touch icons -->
<link href='<%= asset_path 'apple-touch-icon.png' %>' rel='apple-touch-icon'>
<link href='<%= asset_path 'apple-touch-icon-72x72.png' %>' rel='apple-touch-icon' sizes='72x72'>
<link href='<%= asset_path 'apple-touch-icon-114x114.png' %>' rel='apple-touch-icon' sizes='114x114'>
<link href='<%= asset_path 'apple-touch-icon-144x144.png' %>' rel='apple-touch-icon' sizes='144x144'>

<!-- Placed at the top of the document 'cause of turbolinks -->
<%= javascript_include_tag 'application' %>
</head>
<body>
  <%= render 'shared/navbar' %>
  <div class='container' id='main-container'>
    <div class='content push'>
      <%= yield %>
    </div>
  </div>
  <div id='footer'>
    <div class='container'>
      <%= render 'shared/footer' %>
    </div>
  </div>
</body>
</html>

app/views/services/index.html.erb
<div class="row">
  <div class="offset1 span10">
    <% @providers.each do |provider| %>
      <div class="span2">
        <h3><%= provider.capitalize %></h3>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_footer.html.erb
<hr/>
<footer/>

app/views/shared/_navbar.html.erb
<div class='navbar navbar-default push'>
  <div class='container'>
    <div class='container'>
      <div class="navbar-header pull-right">
        <% if logged_in? %>
          <div class="navbar-text navbar-right">Logged in as, <strong><%= current_user.name %></strong> |         
            <%= link_to 'Logout', logout_path %>
		      </div>
        <% end %>
      </div>
      <div class="navbar-header">
        <%= link_to Rails.application.class.parent_name.upcase, root_path, class: 'navbar-brand' %>
      </div>
      <ul class="nav navbar-nav">
        <li class="<%= active_nav('index') %>"><%= link_to 'Home', root_path %></li>
        <li class="<%= active_nav('report') %>"><%= link_to 'link', '#'%></li>
      </ul>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>